import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

import { decimalTransformer } from '../../database/decimal.transformer';

import { Loan } from './loan.entity';

export enum InstallmentStatus {
  Pending = 'pending',
  Paid = 'paid',
  Cancelled = 'cancelled',
}

@Entity('installments')
export class Installment {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Index()
  @Column()
  loanId!: string;

  @ManyToOne(() => Loan, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'loan_id' })
  loan!: Loan;

  @Column()
  installmentNumber!: number;

  @Column({
    type: 'decimal',
    precision: 12,
    scale: 2,
    transformer: decimalTransformer,
  })
  amount!: number;

  // The capital-only portion of `amount`, generated by the amortization
  // schedule (see loans/amortization/generateSchedule.ts). Nullable because
  // installments predating Phase 14 (created before this column existed —
  // amount was a single hand-entered total with no capital/interest split)
  // never had this calculated. Used by
  // docs/phases/PHASE_16_EARLY_PAYOFF.md and
  // docs/phases/PHASE_17_REFINANCING_RECALC.md to compute interest caused
  // vs. principal remaining.
  @Column({
    type: 'decimal',
    precision: 12,
    scale: 2,
    nullable: true,
    transformer: decimalTransformer,
  })
  principalPortion!: number | null;

  @Index()
  @Column({ type: 'date' })
  dueDate!: string;

  @Index()
  @Column({
    type: 'enum',
    enum: InstallmentStatus,
    default: InstallmentStatus.Pending,
  })
  status!: InstallmentStatus;

  // A down payment made at/near disbursement — not a scheduled repayment
  // the client can be "late" on, so it never accrues mora regardless of
  // due_date. See docs/phases/PHASE_13_INITIAL_INSTALLMENT.md.
  @Column({ default: false })
  isInitial!: boolean;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;

  @DeleteDateColumn()
  deletedAt!: Date | null;
}
