import { apiClient } from '@/lib/apiClient';

import type {
  Installment,
  Payment,
} from '@/features/installments/installmentsApi';
import type { ConceptCalculationType } from '@/features/interestConceptTypes/interestConceptTypesApi';

// Matches apps/api/src/loans/entities/loan.entity.ts exactly.
export enum InstallmentFrequency {
  Monthly = 'monthly',
  Biweekly = 'biweekly',
}

export enum LoanStatus {
  Active = 'active',
  Paid = 'paid',
  Refinanced = 'refinanced',
}

export interface Loan {
  id: string;
  clientId: string;
  promissoryNoteNumber: string;
  principalAmount: number;
  interestRate: number;
  disbursedAt: string;
  installmentFrequency: InstallmentFrequency;
  totalInstallments: number;
  status: LoanStatus;
  refinancedFromLoanId: string | null;
  description: string | null;
  // Snapshotted once at creation/refinance time, not recomputed later — a
  // warning, never a block. See docs/phases/PHASE_15_USURY_RATE.md.
  usuryCeilingExceededAtCreation: boolean;
  usuryJustification: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

// GET /loans (list) return shape — matches apps/api's LoanSummary. Added
// specifically for the standalone "Préstamos" screen (F-16/17), which is a
// different view from Clientes and needs to show whose loan it is plus
// collection status without opening it. clientFullName/outstandingBalance/
// installmentsPaid/overdueDays didn't exist on the API until this phase —
// LoansService.findAll now joins `client` and aggregates installments per
// loan to compute them. See DESIGN_TOKENS.md "Known design/backend gaps".
export interface LoanSummary extends Loan {
  clientFullName: string;
  outstandingBalance: number;
  installmentsPaid: number;
  overdueDays: number;
  // The due date of the oldest still-pending installment, whether it's
  // already overdue or upcoming — null when nothing's pending anymore
  // (fully paid/cancelled). Added post-Phase-5, client request: see
  // apps/client/docs/DESIGN_TOKENS.md "Known design/backend gaps".
  nextInstallmentDueDate: string | null;
  // Sum of totalDue across ONLY the overdue installments — unlike
  // outstandingBalance, which includes every pending installment whether
  // overdue or not. Use this one for "how much is actually late" (e.g. the
  // client's "En mora" stat); use outstandingBalance for "how much is left
  // on the whole loan". Added post-Phase-5, client request: see
  // apps/client/docs/DESIGN_TOKENS.md "Known design/backend gaps".
  overdueBalance: number;
}

// GET /loans/:id return shape (apps/api's LoanDetail). Does NOT include
// clientFullName — only the list endpoint (LoanSummary) was extended with
// it, since the detail page is always reached with the client already
// known (from the list row or ClientDetailPage).
export interface LoanDetail extends Loan {
  installments: Installment[];
  // Computed reverse lookup: the loan this one was later refinanced into,
  // if any. Only relevant once Phase 6 (refinancing) ships.
  refinancedToLoanId: string | null;
}

export interface LoansQueryParams {
  clientId?: string;
  status?: LoanStatus;
  // Matches client name or promissory note number — added to
  // QueryLoansDto/LoansService.findAll for the Préstamos list's search box.
  search?: string;
  page?: number;
  limit?: number;
}

export interface PaginatedLoans {
  items: LoanSummary[];
  meta: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// Matches apps/api/src/loans/dto/loanConceptAssignment.dto.ts's
// LoanConceptAssignmentDto exactly.
export interface LoanConceptAssignment {
  conceptTypeId: string;
  calculationType: ConceptCalculationType;
  value: number;
}

// Matches InstallmentConceptOverrideDto exactly — lets a specific
// installment use different concepts than the loan's baseline. Not
// currently exposed in LoanForm.tsx/RefinanceLoanForm.tsx (expected to be
// a rare case); the type exists so the API contract is complete and the UI
// can add it later without a backend change.
export interface InstallmentConceptOverride {
  installmentNumber: number;
  concepts: LoanConceptAssignment[];
}

// Matches apps/api/src/loans/dto/createLoan.dto.ts exactly. As of Phase 14
// the installment schedule is generated by the API from principalAmount,
// totalInstallments, and concepts — no more hand-entered
// installmentAmounts. interestRate is used only for moratory interest on
// overdue installments (docs/phases/PHASE_14_INTEREST_CONCEPTS.md).
export interface CreateLoanInput {
  clientId: string;
  promissoryNoteNumber: string;
  principalAmount: number;
  interestRate: number;
  disbursedAt: string;
  installmentFrequency: InstallmentFrequency;
  totalInstallments: number;
  concepts: LoanConceptAssignment[];
  installmentConceptOverrides?: InstallmentConceptOverride[];
  // 0-based index into the generated schedule marking the "cuota inicial" —
  // exempt from mora regardless of due date. Undefined when the loan has
  // no initial installment. See docs/phases/PHASE_13_INITIAL_INSTALLMENT.md.
  initialInstallmentIndex?: number;
  description?: string;
  // Optional note explaining why the loan proceeds despite exceeding the
  // current usury ceiling — only meaningful when usuryWarning from
  // previewSchedule() actually fired. See docs/phases/PHASE_15_USURY_RATE.md.
  usuryJustification?: string;
}

// Matches apps/api/src/loans/dto/previewSchedule.dto.ts exactly — the
// schedule-relevant subset of CreateLoanInput, for POST /loans/preview-schedule.
export type PreviewScheduleInput = Omit<
  CreateLoanInput,
  | 'clientId'
  | 'promissoryNoteNumber'
  | 'interestRate'
  | 'description'
  | 'usuryJustification'
>;

// Matches apps/api/src/loans/loans.service.ts's PreviewedInstallment exactly.
export interface PreviewedInstallment {
  installmentNumber: number;
  dueDate: string;
  principalPortion: number;
  amount: number;
  conceptBreakdown: { name: string; amount: number }[];
}

// Matches apps/api/src/loans/loans.service.ts's UsuryWarning exactly —
// present (non-null) only when the schedule's highest per-installment
// effective rate exceeds the current usury ceiling. A warning the admin
// can proceed past, never a hard block.
export interface UsuryWarning {
  maxEffectiveInstallmentRate: number;
  currentCeilingRate: number;
}

export interface SchedulePreview {
  installments: PreviewedInstallment[];
  usuryWarning: UsuryWarning | null;
}

// Matches apps/api/src/loans/payoff/calculatePayoff.ts's PayoffQuote
// exactly. See docs/phases/PHASE_16_EARLY_PAYOFF.md — a not-yet-due
// installment contributes only principalApplied (its principalPortion),
// at face value, with interestApplied 0; a matured (due/overdue)
// installment's interestApplied includes both Phase 14 concept charges and
// any moratory interest.
export interface PayoffInstallmentBreakdown {
  installmentId: string;
  installmentNumber: number;
  interestApplied: number;
  principalApplied: number;
  totalDue: number;
}

export interface PayoffQuote {
  installments: PayoffInstallmentBreakdown[];
  totalInterestOwed: number;
  totalPrincipalOwed: number;
  totalDue: number;
}

// Matches apps/api/src/loans/dto/updateLoan.dto.ts exactly — only these two
// fields are editable post-creation. principalAmount/schedule are NOT
// patchable (would cascade into already-generated installments, out of
// scope per the DTO's own comment).
export interface UpdateLoanInput {
  interestRate?: number;
  description?: string;
}

// Matches apps/api/src/loans/dto/refinanceLoan.dto.ts exactly — same shape
// as CreateLoanInput minus clientId (the new loan always belongs to the
// same client as the one being refinanced, enforced server-side). Phase 6:
// POST /loans/:id/refinance closes the old loan out (status: 'refinanced',
// its remaining pending installments marked 'cancelled' — confirmed
// business decision, see docs/DATABASE.md "Refinancing") and creates this
// new loan linked back via refinancedFromLoanId. Its schedule is generated
// the same way as loan creation, as of Phase 14.
export interface RefinanceLoanInput {
  promissoryNoteNumber: string;
  principalAmount: number;
  interestRate: number;
  disbursedAt: string;
  installmentFrequency: InstallmentFrequency;
  totalInstallments: number;
  concepts: LoanConceptAssignment[];
  installmentConceptOverrides?: InstallmentConceptOverride[];
  description?: string;
  // See CreateLoanInput.usuryJustification.
  usuryJustification?: string;
}

export const loansApi = {
  getAll: async (params: LoansQueryParams = {}): Promise<PaginatedLoans> => {
    const { data, meta } = await apiClient.get<LoanSummary[]>('/loans', {
      clientId: params.clientId,
      status: params.status,
      search: params.search,
      page: params.page,
      limit: params.limit,
    });
    return { items: data, meta: meta as PaginatedLoans['meta'] };
  },

  getOne: async (id: string): Promise<LoanDetail> => {
    const { data } = await apiClient.get<LoanDetail>(`/loans/${id}`);
    return data;
  },

  // Admin only — enforced server-side via @Roles(UserRole.Admin); the UI
  // still hides the action for non-admins, consistent with Clientes.
  create: async (input: CreateLoanInput): Promise<LoanDetail> => {
    const { data } = await apiClient.post<LoanDetail>('/loans', input);
    return data;
  },

  // Runs the same schedule generation as create()/refinance() without
  // persisting anything — lets LoanForm.tsx/RefinanceLoanForm.tsx show the
  // admin what the installments will look like before they submit.
  previewSchedule: async (
    input: PreviewScheduleInput,
  ): Promise<SchedulePreview> => {
    const { data } = await apiClient.post<SchedulePreview>(
      '/loans/preview-schedule',
      input,
    );
    return data;
  },

  update: async (id: string, input: UpdateLoanInput): Promise<Loan> => {
    const { data } = await apiClient.patch<Loan>(`/loans/${id}`, input);
    return data;
  },

  // Added for the loan detail screen's "Historial de pagos" (F-19) — there
  // was previously no way to list a loan's payments at all on the backend,
  // only register one. See LoansService.getPayments.
  getPayments: async (id: string): Promise<Payment[]> => {
    const { data } = await apiClient.get<Payment[]>(`/loans/${id}/payments`);
    return data;
  },

  // Backs F-22 "Cambiar estado" — but only the "Pagado" transition is
  // real; "Al día"/"En mora" aren't stored states (see the gaps note in
  // DESIGN_TOKENS.md), so this is the one manual override that exists:
  // closing a loan out as paid without a per-installment payment trail
  // (e.g. the client paid in cash outside the system). Admin only.
  markAsPaid: async (id: string): Promise<LoanDetail> => {
    const { data } = await apiClient.post<LoanDetail>(
      `/loans/${id}/mark-as-paid`,
    );
    return data;
  },

  // Read-only, safe to call regardless of the loan's status — see
  // docs/phases/PHASE_16_EARLY_PAYOFF.md.
  getPayoffQuote: async (id: string): Promise<PayoffQuote> => {
    const { data } = await apiClient.get<PayoffQuote>(
      `/loans/${id}/payoff-quote`,
    );
    return data;
  },

  // Separate, explicit flow from registering an ordinary payment — always
  // settles the FULL payoff quote, closing the loan out. Admin only.
  payoff: async (id: string): Promise<LoanDetail> => {
    const { data } = await apiClient.post<LoanDetail>(`/loans/${id}/payoff`);
    return data;
  },

  // Admin only — enforced server-side. Returns the newly-created loan
  // (with its generated installments), not the old one — the caller
  // navigates there after a successful refinance.
  refinance: async (
    id: string,
    input: RefinanceLoanInput,
  ): Promise<LoanDetail> => {
    const { data } = await apiClient.post<LoanDetail>(
      `/loans/${id}/refinance`,
      input,
    );
    return data;
  },
};
